# -*- coding: utf-8 -*-
"""
Definiciones bilingues para las palabras de PARES MINIMOS de HEAR IT
que no existian en definitions.json.
Estilo: una frase corta, para estudiantes de ingles.
"""

PAIR_DEFS = {
"ADVISE": ("to tell someone what you think they should do", "decirle a alguien lo que crees que deberia hacer"),
"AIR": ("the gas we breathe", "el gas que respiramos"),
"AND": ("a word used to join two things", "una palabra que une dos cosas"),
"ATE": ("past form of eat", "forma pasada de comer"),
"AXE": ("a tool with a blade for cutting wood", "una herramienta con hoja para cortar madera"),
"BAD": ("not good", "que no es bueno"),
"BAIL": ("money paid so someone can leave jail while waiting for trial", "dinero que se paga para que alguien salga de la carcel mientras espera juicio"),
"BAN": ("to officially forbid something", "prohibir algo oficialmente"),
"BASE": ("the bottom part that supports something", "la parte de abajo que sostiene algo"),
"BEAN": ("a small seed eaten as food", "una semilla pequena que se come"),
"BEAT": ("to hit repeatedly, or to win against someone", "golpear repetidamente, o ganarle a alguien"),
"BEG": ("to ask for something very strongly", "pedir algo con mucha insistencia"),
"BEND": ("to make something curved", "hacer que algo se curve"),
"BERRY": ("a small round soft fruit", "una fruta pequena, redonda y blanda"),
"BEST": ("better than all the others", "mejor que todos los demas"),
"BIN": ("a container for putting things in", "un recipiente para meter cosas"),
"BIT": ("a small piece or amount", "un trozo o una cantidad pequena"),
"BOG": ("soft wet ground you can sink into", "terreno blando y mojado donde te puedes hundir"),
"BOWL": ("a round deep dish for food", "un plato hondo y redondo para comida"),
"BUG": ("a small insect", "un insecto pequeno"),
"BUZZ": ("the sound a bee makes", "el sonido que hace una abeja"),
"CAT": ("a small animal kept as a pet", "un animal pequeno que se tiene de mascota"),
"CATCH": ("to take hold of something moving", "agarrar algo que se mueve"),
"CHEAP": ("costing little money", "que cuesta poco dinero"),
"CHEAT": ("to break the rules to win", "romper las reglas para ganar"),
"CHIN": ("the part of your face below your mouth", "la parte de la cara debajo de la boca"),
"CHIP": ("a thin slice of fried potato", "una rodaja fina de papa frita"),
"CHOOSE": ("to pick one thing from several", "elegir una cosa entre varias"),
"CHOP": ("to cut into pieces with a knife", "cortar en trozos con un cuchillo"),
"COOK": ("to prepare food with heat", "preparar comida con calor"),
"COP": ("an informal word for a police officer", "palabra informal para un policia"),
"COT": ("a small simple bed", "una cama pequena y sencilla"),
"CUP": ("a small container you drink from", "un recipiente pequeno para beber"),
"CURB": ("the edge of the sidewalk next to the street", "el borde de la acera junto a la calle"),
"CURVE": ("a line that bends smoothly", "una linea que se dobla suavemente"),
"CUT": ("to divide something with a sharp tool", "dividir algo con algo filoso"),
"DAD": ("an informal word for father", "palabra informal para padre"),
"DARE": ("to be brave enough to do something", "atreverse a hacer algo"),
"DEAD": ("no longer alive", "que ya no esta vivo"),
"DEN": ("the home of a wild animal", "la guarida de un animal salvaje"),
"DIP": ("to put something quickly into a liquid", "meter algo rapido en un liquido"),
"DOCK": ("a place where boats stop", "un lugar donde se detienen los barcos"),
"EACH": ("every one of a group, one by one", "cada uno de un grupo, uno por uno"),
"EAT": ("to put food in your mouth and swallow it", "meter comida en la boca y tragarla"),
"EDGE": ("the outer line where something ends", "la linea exterior donde algo termina"),
"END": ("the final part of something", "la parte final de algo"),
"EYES": ("the parts of your body you see with", "las partes del cuerpo con las que ves"),
"FEEL": ("to experience an emotion or a touch", "experimentar una emocion o un contacto"),
"FEET": ("more than one foot", "mas de un pie"),
"FILL": ("to make something full", "hacer que algo quede lleno"),
"FLASH": ("a sudden bright light", "una luz brillante y repentina"),
"FLESH": ("the soft part of the body under the skin", "la parte blanda del cuerpo bajo la piel"),
"FOOD": ("what people and animals eat", "lo que comen las personas y los animales"),
"FOOL": ("a person who acts in a silly way", "una persona que actua tontamente"),
"FULL": ("with no space left inside", "sin espacio libre adentro"),
"GUESS": ("to give an answer without being sure", "dar una respuesta sin estar seguro"),
"HAD": ("past form of have", "forma pasada de tener"),
"HARM": ("damage or injury", "dano o perjuicio"),
"HATE": ("to dislike something very strongly", "sentir un rechazo muy fuerte por algo"),
"HEAR": ("to receive sound with your ears", "recibir sonido con los oidos"),
"HEAT": ("the quality of being hot", "la cualidad de estar caliente"),
"HEEL": ("the back part of your foot", "la parte de atras del pie"),
"HIGH": ("far above the ground", "muy por encima del suelo"),
"HILL": ("a small mountain", "una montana pequena"),
"HIT": ("to strike something", "golpear algo"),
"HOLD": ("to keep something in your hand", "sostener algo con la mano"),
"HONE": ("to make a skill sharper with practice", "afinar una habilidad con practica"),
"HOT": ("having a high temperature", "que tiene temperatura alta"),
"HUT": ("a small simple house", "una casa pequena y sencilla"),
"ILL": ("not healthy, sick", "que no esta sano, enfermo"),
"ITCH": ("an uncomfortable feeling that makes you scratch", "una sensacion incomoda que te hace rascarte"),
"JAM": ("sweet food made from fruit and sugar", "alimento dulce hecho de fruta y azucar"),
"JEER": ("to shout rudely at someone", "gritarle a alguien con burla"),
"JELL": ("to become firm like jelly", "cuajar, ponerse firme como gelatina"),
"JET": ("a fast airplane", "un avion rapido"),
"JOKE": ("something said to make people laugh", "algo que se dice para hacer reir"),
"KOOK": ("a strange or crazy person", "una persona rara o loca"),
"LAND": ("the solid part of the earth", "la parte solida de la tierra"),
"LEAST": ("the smallest amount", "la cantidad mas pequena"),
"LEND": ("to give something for a short time", "dar algo por un tiempo corto"),
"LIST": ("words or items written one under another", "palabras o cosas escritas una debajo de otra"),
"LIVE": ("to be alive, or to have your home somewhere", "estar vivo, o tener tu hogar en un lugar"),
"LOCK": ("a device that keeps a door closed", "un mecanismo que mantiene cerrada una puerta"),
"LOOK": ("to turn your eyes toward something", "dirigir los ojos hacia algo"),
"LOOSE": ("not tight, not firmly fixed", "que no esta apretado ni bien sujeto"),
"LOSE": ("to no longer have something", "dejar de tener algo"),
"LUCK": ("good things that happen by chance", "cosas buenas que pasan por azar"),
"LUKE": ("a male first name", "un nombre propio masculino"),
"MAN": ("an adult male person", "una persona adulta de sexo masculino"),
"MARBLE": ("a hard stone used in buildings and statues", "una piedra dura usada en edificios y estatuas"),
"MARVEL": ("something wonderful, or to be amazed by it", "algo maravilloso, o asombrarse por ello"),
"MASS": ("a large amount of something", "una gran cantidad de algo"),
"MAT": ("a small flat piece of material for the floor", "una pieza plana y pequena para el piso"),
"MEAL": ("the food you eat at one time", "la comida que se come en una sola vez"),
"MEET": ("to come together with someone", "reunirse con alguien"),
"MEN": ("more than one man", "mas de un hombre"),
"MESS": ("a dirty or disordered state", "un estado sucio o desordenado"),
"MET": ("past form of meet", "forma pasada de encontrarse"),
"MILL": ("a building where grain is made into flour", "un edificio donde el grano se convierte en harina"),
"MIT": ("a thick glove used in baseball", "un guante grueso usado en beisbol"),
"MOUSE": ("a very small animal with a long tail", "un animal muy pequeno con cola larga"),
"MUCH": ("a large amount", "una gran cantidad"),
"MUSH": ("soft wet food with no shape", "comida blanda y aguada sin forma"),
"NOT": ("a word used to say something is false", "palabra que se usa para negar"),
"NUT": ("a hard dry fruit with a shell", "un fruto seco y duro con cascara"),
"OLD": ("having lived or existed a long time", "que ha vivido o existido mucho tiempo"),
"OWN": ("to have something as your property", "tener algo como propiedad"),
"PASS": ("to move by, or to succeed in a test", "pasar de largo, o aprobar un examen"),
"PATH": ("a narrow way for walking", "un camino angosto para caminar"),
"PEACE": ("a time with no war or fighting", "un tiempo sin guerra ni peleas"),
"PEAK": ("the highest point", "el punto mas alto"),
"PEAS": ("small round green vegetables", "vegetales pequenos, redondos y verdes"),
"PEEL": ("to remove the skin from a fruit", "quitarle la cascara a una fruta"),
"PICK": ("to choose or to take something up", "elegir o recoger algo"),
"PILL": ("a small round piece of medicine", "una pastilla pequena de medicina"),
"PLACE": ("a particular position or area", "una posicion o zona determinada"),
"PLAYS": ("does something for fun, or theater works", "juega, o obras de teatro"),
"PRIZE": ("something you win", "algo que se gana"),
"PULL": ("to move something toward you", "mover algo hacia ti"),
"RACE": ("a competition of speed", "una competencia de velocidad"),
"RAISE": ("to lift something up", "levantar algo"),
"REACH": ("to arrive at, or to stretch out to touch", "llegar a, o estirarse para tocar"),
"RICH": ("having a lot of money", "que tiene mucho dinero"),
"RISE": ("to move upward", "subir, moverse hacia arriba"),
"ROB": ("to take something illegally from someone", "quitarle algo a alguien ilegalmente"),
"RUB": ("to move your hand over a surface with pressure", "pasar la mano por una superficie haciendo presion"),
"SAID": ("past form of say", "forma pasada de decir"),
"SAT": ("past form of sit", "forma pasada de sentarse"),
"SCENE": ("a part of a movie or play", "una parte de una pelicula u obra"),
"SEND": ("to make something go to another place", "hacer que algo vaya a otro lugar"),
"SET": ("a group of things that go together", "un grupo de cosas que van juntas"),
"SHEET": ("a thin flat piece of paper or cloth", "una pieza fina y plana de papel o tela"),
"SHERRY": ("a strong wine from Spain", "un vino fuerte de Espana"),
"SHIN": ("the front part of your leg below the knee", "la parte delantera de la pierna bajo la rodilla"),
"SHOP": ("a place where things are sold", "un lugar donde se venden cosas"),
"SHOT": ("the act of firing a gun or kicking a ball", "el disparo de un arma o el tiro de un balon"),
"SHUT": ("to close something", "cerrar algo"),
"SICK": ("not healthy", "que no esta sano"),
"SIN": ("an act that breaks a religious rule", "un acto que rompe una regla religiosa"),
"SINK": ("to go down under water", "hundirse bajo el agua"),
"SIT": ("to rest with your body on a chair", "descansar con el cuerpo sobre una silla"),
"SLEEP": ("to rest with your eyes closed at night", "descansar con los ojos cerrados de noche"),
"SLIP": ("to slide and lose your balance", "resbalar y perder el equilibrio"),
"SONG": ("music with words that you sing", "musica con palabras que se canta"),
"STEEL": ("a strong metal made from iron", "un metal fuerte hecho de hierro"),
"STOCK": ("goods available in a shop, or a share of a company", "mercancia disponible en una tienda, o una accion de una empresa"),
"STUCK": ("unable to move", "que no se puede mover"),
"SUNG": ("past participle of sing", "participio pasado de cantar"),
"TANK": ("a large container for liquid", "un recipiente grande para liquido"),
"TAUGHT": ("past form of teach", "forma pasada de ensenar"),
"TEEN": ("a person between 13 and 19 years old", "una persona de entre 13 y 19 anos"),
"TEN": ("the number 10", "el numero 10"),
"THANK": ("to say you are grateful", "decir que estas agradecido"),
"THEN": ("at that time, or after that", "en ese momento, o despues de eso"),
"THERE": ("in that place", "en ese lugar"),
"THEY": ("the word used for more than one person", "la palabra que se usa para mas de una persona"),
"THICK": ("wide from one side to the other", "ancho de un lado al otro"),
"THIN": ("not thick, or not fat", "que no es grueso, o que no es gordo"),
"THINK": ("to use your mind to form ideas", "usar la mente para formar ideas"),
"TIN": ("a soft silver metal, or a metal container", "un metal plateado y blando, o una lata"),
"VASE": ("a container for holding flowers", "un recipiente para poner flores"),
"VAT": ("a very large container for liquid", "un recipiente muy grande para liquido"),
"VEIL": ("a thin cloth that covers the face", "una tela fina que cubre la cara"),
"VERSE": ("a part of a song or poem", "una parte de una cancion o un poema"),
"VERY": ("used to make a word stronger", "se usa para reforzar una palabra"),
"VEST": ("a piece of clothing with no sleeves", "una prenda sin mangas"),
"VET": ("a doctor for animals", "un medico de animales"),
"VILE": ("extremely unpleasant or evil", "extremadamente desagradable o malvado"),
"VINE": ("a climbing plant that grapes grow on", "una planta trepadora donde crecen las uvas"),
"VOLE": ("a small animal like a mouse", "un animal pequeno parecido a un raton"),
"VOLT": ("a unit that measures electricity", "una unidad que mide la electricidad"),
"VOTE": ("to choose in an election", "elegir en una eleccion"),
"WAIL": ("to cry loudly with a long sound", "llorar fuerte con un sonido largo"),
"WASH": ("to clean with water", "limpiar con agua"),
"WATCH": ("to look at something for a while", "mirar algo durante un rato"),
"WEST": ("the direction where the sun goes down", "la direccion por donde se oculta el sol"),
"WHILE": ("during the time that", "durante el tiempo en que"),
"WILL": ("used to talk about the future", "se usa para hablar del futuro"),
"WINE": ("an alcoholic drink made from grapes", "una bebida alcoholica hecha de uvas"),
"WISH": ("to want something to happen", "querer que algo pase"),
"WITCH": ("a woman with magic powers in stories", "una mujer con poderes magicos en los cuentos"),
"WORSE": ("more bad than something else", "mas malo que otra cosa"),
"YAM": ("a vegetable that grows underground", "un tuberculo que crece bajo tierra"),
"YEAR": ("a period of twelve months", "un periodo de doce meses"),
"YET": ("until now, up to this time", "hasta ahora, hasta este momento"),
"YOKE": ("a wooden bar joining two animals to pull a load", "una barra de madera que une dos animales para tirar de una carga"),
"EX": ("a person you used to be in a relationship with", "una persona con la que tuviste una relacion"),
}
