# -*- coding: utf-8 -*-
"""
Sets NUEVOS para IMPOSTOR, todos basados en SIGNIFICADO.
Reemplazan a los 84 sets de criterio gramatical (verbo vs sustantivo).

Formato por set:
    (palabras[5], impostora, tipo, explicacion_en, explicacion_es)

tipo:  "semantic"  -> pertenecen al mismo campo o situacion
       "synonym"   -> significan practicamente lo mismo
"""

NEW_SETS = {

# ══════════════════════════════════════════════════════════
("business", "basic"): [
 (["BOSS","MANAGER","DIRECTOR","LEADER","CLIENT"],"CLIENT","synonym",
  "BOSS, MANAGER, DIRECTOR and LEADER are all people in charge; a CLIENT is someone who buys from you.",
  "BOSS, MANAGER, DIRECTOR y LEADER son personas al mando; un CLIENT es alguien que te compra."),
 (["MONEY","CASH","FUNDS","CAPITAL","DEBT"],"DEBT","synonym",
  "The first four all mean money you have; DEBT is money you owe.",
  "Las primeras cuatro significan dinero que tienes; DEBT es dinero que debes."),
 (["OFFICE","DESK","PRINTER","COMPUTER","GARDEN"],"GARDEN","semantic",
  "All are things you find in a workplace; a GARDEN is not.",
  "Todos son cosas de un lugar de trabajo; un GARDEN no lo es."),
 (["SALARY","WAGE","PAY","INCOME","EXPENSE"],"EXPENSE","synonym",
  "The first four mean money you receive for working; an EXPENSE is money you spend.",
  "Las primeras cuatro son dinero que recibes por trabajar; un EXPENSE es dinero que gastas."),
 (["BUYER","CUSTOMER","CLIENT","SHOPPER","SELLER"],"SELLER","synonym",
  "The first four all mean the person who buys; the SELLER is the opposite side.",
  "Las primeras cuatro son la persona que compra; el SELLER es el lado opuesto."),
 (["MEETING","CONFERENCE","INTERVIEW","PRESENTATION","VACATION"],"VACATION","semantic",
  "All are work events; a VACATION is time away from work.",
  "Todos son eventos de trabajo; VACATION es tiempo fuera del trabajo."),
 (["PROFIT","GAIN","EARNINGS","REVENUE","LOSS"],"LOSS","synonym",
  "The first four mean money the business makes; a LOSS is money it does not.",
  "Las primeras cuatro son dinero que gana el negocio; LOSS es dinero que no gana."),
 (["EMAIL","PHONE","LETTER","MESSAGE","CHAIR"],"CHAIR","semantic",
  "All are ways to communicate at work; a CHAIR is furniture.",
  "Todos son formas de comunicarse en el trabajo; CHAIR es un mueble."),
 (["COMPANY","FIRM","BUSINESS","ENTERPRISE","EMPLOYEE"],"EMPLOYEE","synonym",
  "The first four all mean an organization; an EMPLOYEE is a person who works in one.",
  "Las primeras cuatro significan una organizacion; un EMPLOYEE es una persona que trabaja en ella."),
 (["CONTRACT","AGREEMENT","DEAL","ARRANGEMENT","ARGUMENT"],"ARGUMENT","synonym",
  "The first four mean something both sides accept; an ARGUMENT is a disagreement.",
  "Las primeras cuatro son algo que ambas partes aceptan; un ARGUMENT es un desacuerdo."),
 (["BANK","ATM","CARD","ACCOUNT","KITCHEN"],"KITCHEN","semantic",
  "All are related to handling money; a KITCHEN is not.",
  "Todos se relacionan con manejar dinero; una KITCHEN no."),
 (["CHEAP","AFFORDABLE","INEXPENSIVE","ECONOMICAL","EXPENSIVE"],"EXPENSIVE","synonym",
  "The first four all mean low in price; EXPENSIVE means the opposite.",
  "Las primeras cuatro significan de precio bajo; EXPENSIVE significa lo contrario."),
],

("business", "intermediate"): [
 (["INVOICE","RECEIPT","BILL","STATEMENT","CATALOG"],"CATALOG","semantic",
  "All are documents about money owed or paid; a CATALOG shows products.",
  "Todos son documentos sobre dinero debido o pagado; un CATALOG muestra productos."),
 (["DEADLINE","SCHEDULE","TIMELINE","AGENDA","BONUS"],"BONUS","semantic",
  "All are about organizing time; a BONUS is extra money.",
  "Todos son sobre organizar el tiempo; un BONUS es dinero extra."),
 (["SUPPLIER","VENDOR","PROVIDER","DISTRIBUTOR","COMPETITOR"],"COMPETITOR","synonym",
  "The first four all mean a company that sells you goods; a COMPETITOR fights you for customers.",
  "Las primeras cuatro son una empresa que te vende bienes; un COMPETITOR te disputa los clientes."),
 (["PROMOTION","RAISE","BONUS","REWARD","DISMISSAL"],"DISMISSAL","semantic",
  "All are good things you can get at work; a DISMISSAL means losing your job.",
  "Todos son cosas buenas que puedes recibir en el trabajo; DISMISSAL es perder el empleo."),
 (["BUDGET","FORECAST","ESTIMATE","PROJECTION","REFUND"],"REFUND","synonym",
  "The first four are predictions about future money; a REFUND is money given back.",
  "Las primeras cuatro son predicciones sobre dinero futuro; un REFUND es dinero devuelto."),
 (["WAREHOUSE","FACTORY","STORE","OFFICE","PASSPORT"],"PASSPORT","semantic",
  "All are places where a business operates; a PASSPORT is a travel document.",
  "Todos son lugares donde opera un negocio; un PASSPORT es un documento de viaje."),
 (["TRAINING","WORKSHOP","COURSE","SEMINAR","RESIGNATION"],"RESIGNATION","semantic",
  "All are ways to learn at work; a RESIGNATION is quitting your job.",
  "Todos son formas de aprender en el trabajo; RESIGNATION es renunciar."),
 (["SHAREHOLDER","INVESTOR","PARTNER","STAKEHOLDER","INTERN"],"INTERN","synonym",
  "The first four all have a financial stake in the company; an INTERN is a trainee.",
  "Las primeras cuatro tienen participacion financiera en la empresa; un INTERN es un aprendiz."),
 (["DISCOUNT","SALE","OFFER","DEAL","SURCHARGE"],"SURCHARGE","synonym",
  "The first four mean a lower price; a SURCHARGE is an extra charge.",
  "Las primeras cuatro significan un precio menor; un SURCHARGE es un cargo extra."),
 (["STRATEGY","PLAN","APPROACH","METHOD","OUTCOME"],"OUTCOME","synonym",
  "The first four are how you intend to do something; an OUTCOME is the result.",
  "Las primeras cuatro son como piensas hacer algo; un OUTCOME es el resultado."),
 (["NETWORKING","MEETING","PITCHING","NEGOTIATING","FILING"],"FILING","semantic",
  "All are ways of dealing with people in business; FILING is organizing documents alone.",
  "Todos son formas de tratar con personas en los negocios; FILING es ordenar documentos solo."),
 (["REVENUE","TURNOVER","SALES","INCOME","OVERHEAD"],"OVERHEAD","synonym",
  "The first four all mean money coming in; OVERHEAD is the cost of running the business.",
  "Las primeras cuatro son dinero que entra; OVERHEAD es el costo de operar el negocio."),
],

("business", "advanced"): [
 (["LIABILITY","OBLIGATION","DEBT","COMMITMENT","ASSET"],"ASSET","synonym",
  "The first four all mean something you owe; an ASSET is something you own.",
  "Las primeras cuatro significan algo que debes; un ASSET es algo que posees."),
 (["MERGER","ACQUISITION","TAKEOVER","BUYOUT","LAYOFF"],"LAYOFF","semantic",
  "All describe one company absorbing another; a LAYOFF is cutting staff.",
  "Todos describen una empresa absorbiendo otra; un LAYOFF es recortar personal."),
 (["COMPLIANCE","REGULATION","POLICY","GUIDELINE","INCENTIVE"],"INCENTIVE","semantic",
  "All are rules a company must follow; an INCENTIVE is a reward that motivates.",
  "Todos son reglas que la empresa debe cumplir; un INCENTIVE es una recompensa que motiva."),
 (["AUDIT","INSPECTION","REVIEW","EXAMINATION","LAUNCH"],"LAUNCH","synonym",
  "The first four all mean checking something carefully; a LAUNCH is releasing a product.",
  "Las primeras cuatro significan revisar algo con cuidado; un LAUNCH es lanzar un producto."),
 (["LUCRATIVE","PROFITABLE","REWARDING","GAINFUL","WASTEFUL"],"WASTEFUL","synonym",
  "The first four mean producing good money; WASTEFUL means losing it.",
  "Las primeras cuatro significan que produce buen dinero; WASTEFUL significa desperdiciarlo."),
 (["COLLATERAL","GUARANTEE","SECURITY","PLEDGE","DIVIDEND"],"DIVIDEND","synonym",
  "The first four are things promised to secure a loan; a DIVIDEND is a payment to shareholders.",
  "Las primeras cuatro son cosas prometidas para garantizar un prestamo; un DIVIDEND es un pago a los accionistas."),
 (["OUTSOURCE","DELEGATE","SUBCONTRACT","ASSIGN","MONOPOLIZE"],"MONOPOLIZE","synonym",
  "The first four mean giving work to someone else; MONOPOLIZE means keeping everything.",
  "Las primeras cuatro significan dar trabajo a otro; MONOPOLIZE significa quedarse con todo."),
 (["INSOLVENT","BANKRUPT","BROKE","PENNILESS","SOLVENT"],"SOLVENT","synonym",
  "The first four mean unable to pay; SOLVENT means able to pay.",
  "Las primeras cuatro significan no poder pagar; SOLVENT significa poder pagar."),
 (["STAKEHOLDER","INVESTOR","CREDITOR","SHAREHOLDER","APPRENTICE"],"APPRENTICE","semantic",
  "All have a financial interest in the company; an APPRENTICE is learning a trade.",
  "Todos tienen un interes financiero en la empresa; un APPRENTICE esta aprendiendo un oficio."),
 (["ARBITRATION","MEDIATION","NEGOTIATION","SETTLEMENT","LITIGATION"],"LITIGATION","synonym",
  "The first four are ways to solve a conflict by agreement; LITIGATION means going to court.",
  "Las primeras cuatro resuelven un conflicto por acuerdo; LITIGATION es ir a juicio."),
 (["FEASIBLE","VIABLE","PRACTICABLE","WORKABLE","UNREALISTIC"],"UNREALISTIC","synonym",
  "The first four mean possible to do; UNREALISTIC means it cannot work.",
  "Las primeras cuatro significan posible de hacer; UNREALISTIC significa que no puede funcionar."),
 (["PROCUREMENT","PURCHASING","SOURCING","BUYING","RETAILING"],"RETAILING","synonym",
  "The first four all mean acquiring supplies; RETAILING means selling to the public.",
  "Las primeras cuatro son adquirir suministros; RETAILING es vender al publico."),
],

# ══════════════════════════════════════════════════════════
("travel", "basic"): [
 (["PLANE","TRAIN","BUS","TAXI","HOTEL"],"HOTEL","semantic",
  "All are ways to travel; a HOTEL is where you sleep.",
  "Todos son formas de viajar; un HOTEL es donde duermes."),
 (["SUITCASE","BACKPACK","BAG","LUGGAGE","TICKET"],"TICKET","synonym",
  "The first four all mean something you carry your things in; a TICKET is a document.",
  "Las primeras cuatro son algo donde llevas tus cosas; un TICKET es un documento."),
 (["BEACH","MOUNTAIN","LAKE","FOREST","AIRPORT"],"AIRPORT","semantic",
  "All are natural places; an AIRPORT is built by people.",
  "Todos son lugares naturales; un AIRPORT lo construyen las personas."),
 (["MAP","COMPASS","GPS","GUIDE","PILLOW"],"PILLOW","semantic",
  "All help you find your way; a PILLOW helps you sleep.",
  "Todos ayudan a orientarte; una PILLOW ayuda a dormir."),
 (["TRIP","JOURNEY","VOYAGE","TOUR","ARRIVAL"],"ARRIVAL","synonym",
  "The first four all mean travelling somewhere; an ARRIVAL is reaching the end.",
  "Las primeras cuatro significan viajar a algun lado; ARRIVAL es llegar al final."),
 (["PASSPORT","VISA","TICKET","BOARDING PASS","CAMERA"],"CAMERA","semantic",
  "All are documents you need to travel; a CAMERA is optional.",
  "Todos son documentos que necesitas para viajar; una CAMERA es opcional."),
 (["HOTEL","HOSTEL","MOTEL","INN","MUSEUM"],"MUSEUM","synonym",
  "The first four are all places to sleep when travelling; a MUSEUM is a place to visit.",
  "Las primeras cuatro son lugares para dormir viajando; un MUSEUM es un lugar para visitar."),
 (["SUMMER","WINTER","SPRING","AUTUMN","WEEKEND"],"WEEKEND","semantic",
  "All are seasons of the year; a WEEKEND is part of a week.",
  "Todos son estaciones del ano; un WEEKEND es parte de una semana."),
 (["SEA","OCEAN","RIVER","LAKE","DESERT"],"DESERT","semantic",
  "All are places full of water; a DESERT has almost none.",
  "Todos son lugares llenos de agua; un DESERT casi no tiene."),
 (["GUIDE","TOURIST","VISITOR","TRAVELLER","RESIDENT"],"RESIDENT","synonym",
  "The first four are people who come from elsewhere; a RESIDENT lives there.",
  "Las primeras cuatro son personas que vienen de fuera; un RESIDENT vive ahi."),
 (["CHEAP","BUDGET","AFFORDABLE","LOW-PRICED","LUXURY"],"LUXURY","synonym",
  "The first four describe travel that costs little; LUXURY costs a lot.",
  "Las primeras cuatro describen viajes que cuestan poco; LUXURY cuesta mucho."),
 (["WALK","HIKE","STROLL","WANDER","DRIVE"],"DRIVE","synonym",
  "The first four all mean moving on foot; DRIVE means using a car.",
  "Las primeras cuatro significan moverse a pie; DRIVE es usar un carro."),
],

("travel", "intermediate"): [
 (["DEPARTURE","BOARDING","CHECK-IN","TAKEOFF","LANDING"],"LANDING","semantic",
  "All happen before or during leaving; LANDING happens at the end of the flight.",
  "Todos ocurren antes o durante la salida; LANDING ocurre al final del vuelo."),
 (["ITINERARY","SCHEDULE","PLAN","ROUTE","SOUVENIR"],"SOUVENIR","synonym",
  "The first four are about organizing a trip; a SOUVENIR is something you bring home.",
  "Las primeras cuatro son sobre organizar un viaje; un SOUVENIR es algo que traes a casa."),
 (["CUSTOMS","IMMIGRATION","SECURITY","BORDER","LOUNGE"],"LOUNGE","semantic",
  "All are checkpoints you must pass; a LOUNGE is a place to relax.",
  "Todos son controles que debes pasar; un LOUNGE es un lugar para descansar."),
 (["DELAY","CANCELLATION","STRIKE","OVERBOOKING","UPGRADE"],"UPGRADE","semantic",
  "All are problems that ruin a trip; an UPGRADE is good news.",
  "Todos son problemas que arruinan un viaje; un UPGRADE es una buena noticia."),
 (["CURRENCY","EXCHANGE","RATE","CASH","BACKPACK"],"BACKPACK","semantic",
  "All are about handling money abroad; a BACKPACK carries your things.",
  "Todos son sobre manejar dinero en el extranjero; un BACKPACK carga tus cosas."),
 (["ACCOMMODATION","LODGING","HOUSING","SHELTER","TRANSPORT"],"TRANSPORT","synonym",
  "The first four all mean a place to stay; TRANSPORT is how you move.",
  "Las primeras cuatro significan un lugar donde quedarse; TRANSPORT es como te mueves."),
 (["CROWDED","PACKED","BUSY","JAMMED","DESERTED"],"DESERTED","synonym",
  "The first four mean full of people; DESERTED means empty.",
  "Las primeras cuatro significan lleno de gente; DESERTED significa vacio."),
 (["ROUNDTRIP","RETURN","TWO-WAY","BOTH-WAYS","ONE-WAY"],"ONE-WAY","synonym",
  "The first four mean going and coming back; ONE-WAY means you do not return.",
  "Las primeras cuatro significan ir y volver; ONE-WAY significa que no regresas."),
 (["GUIDEBOOK","BROCHURE","LEAFLET","PAMPHLET","SUITCASE"],"SUITCASE","synonym",
  "The first four are all printed information for travellers; a SUITCASE holds clothes.",
  "Las primeras cuatro son informacion impresa para viajeros; una SUITCASE guarda ropa."),
 (["INSURANCE","COVERAGE","PROTECTION","POLICY","DEPOSIT"],"DEPOSIT","synonym",
  "The first four protect you if something goes wrong; a DEPOSIT is money paid in advance.",
  "Las primeras cuatro te protegen si algo sale mal; un DEPOSIT es dinero pagado por adelantado."),
 (["JETLAG","FATIGUE","EXHAUSTION","TIREDNESS","EXCITEMENT"],"EXCITEMENT","synonym",
  "The first four all mean feeling worn out; EXCITEMENT is feeling energized.",
  "Las primeras cuatro significan sentirse agotado; EXCITEMENT es sentirse con energia."),
 (["HARBOR","PORT","DOCK","PIER","RUNWAY"],"RUNWAY","semantic",
  "All are places where boats arrive; a RUNWAY is for planes.",
  "Todos son lugares donde llegan barcos; una RUNWAY es para aviones."),
],

("travel", "advanced"): [
 (["ITINERARY","SCHEDULE","AGENDA","PROGRAM","DESTINATION"],"DESTINATION","synonym",
  "The first four are plans of what you will do; a DESTINATION is where you end up.",
  "Las primeras cuatro son planes de lo que haras; un DESTINATION es donde terminas."),
 (["REMOTE","ISOLATED","SECLUDED","INACCESSIBLE","CENTRAL"],"CENTRAL","synonym",
  "The first four mean far from everything; CENTRAL means right in the middle.",
  "Las primeras cuatro significan lejos de todo; CENTRAL significa justo en el centro."),
 (["EXPEDITION","TREK","PILGRIMAGE","ODYSSEY","LAYOVER"],"LAYOVER","synonym",
  "The first four are long meaningful journeys; a LAYOVER is a short stop between flights.",
  "Las primeras cuatro son viajes largos con proposito; un LAYOVER es una escala corta."),
 (["VISA","PERMIT","AUTHORIZATION","CLEARANCE","BROCHURE"],"BROCHURE","synonym",
  "The first four are official permissions to enter; a BROCHURE is advertising.",
  "Las primeras cuatro son permisos oficiales para entrar; un BROCHURE es publicidad."),
 (["SCENIC","PICTURESQUE","BREATHTAKING","STUNNING","MUNDANE"],"MUNDANE","synonym",
  "The first four describe beautiful views; MUNDANE means ordinary and dull.",
  "Las primeras cuatro describen vistas hermosas; MUNDANE significa ordinario y aburrido."),
 (["RELOCATE","EMIGRATE","MIGRATE","RESETTLE","COMMUTE"],"COMMUTE","synonym",
  "The first four mean moving to live somewhere else; COMMUTE means travelling daily to work.",
  "Las primeras cuatro son mudarse a vivir a otro lugar; COMMUTE es viajar a diario al trabajo."),
 (["RESIDENCY","CITIZENSHIP","NATURALIZATION","SETTLEMENT","DEPORTATION"],"DEPORTATION","semantic",
  "All are ways of gaining the right to stay; DEPORTATION is being forced to leave.",
  "Todos son formas de ganar el derecho a quedarse; DEPORTATION es ser obligado a salir."),
 (["ACCLIMATIZE","ADAPT","ADJUST","SETTLE IN","WITHDRAW"],"WITHDRAW","synonym",
  "The first four mean getting used to a new place; WITHDRAW means pulling away from it.",
  "Las primeras cuatro son acostumbrarse a un lugar nuevo; WITHDRAW es apartarse de el."),
 (["EXCURSION","OUTING","GETAWAY","JAUNT","DEADLINE"],"DEADLINE","synonym",
  "The first four are all short pleasure trips; a DEADLINE is a time limit for work.",
  "Las primeras cuatro son viajes cortos de placer; un DEADLINE es un limite de tiempo laboral."),
 (["TERMINAL","CONCOURSE","GATE","BOARDING AREA","CABIN"],"CABIN","semantic",
  "All are parts of an airport; a CABIN is inside the plane.",
  "Todos son partes de un aeropuerto; una CABIN esta dentro del avion."),
 (["HOSPITABLE","WELCOMING","FRIENDLY","GRACIOUS","HOSTILE"],"HOSTILE","synonym",
  "The first four describe places that treat visitors well; HOSTILE is the opposite.",
  "Las primeras cuatro describen lugares que tratan bien al visitante; HOSTILE es lo contrario."),
 (["STOPOVER","LAYOVER","TRANSIT","CONNECTION","NONSTOP"],"NONSTOP","synonym",
  "The first four all mean breaking the journey; NONSTOP means no break at all.",
  "Las primeras cuatro significan interrumpir el viaje; NONSTOP significa sin ninguna parada."),
],

# ══════════════════════════════════════════════════════════
("daily", "basic"): [
 (["BREAKFAST","LUNCH","DINNER","SNACK","KITCHEN"],"KITCHEN","semantic",
  "All are meals you eat; a KITCHEN is the room where you cook.",
  "Todos son comidas que comes; la KITCHEN es el cuarto donde cocinas."),
 (["SHIRT","PANTS","JACKET","SHOES","MIRROR"],"MIRROR","semantic",
  "All are clothes you wear; a MIRROR is an object you look into.",
  "Todos son ropa que usas; un MIRROR es un objeto en el que te miras."),
 (["HAPPY","GLAD","CHEERFUL","JOYFUL","ANGRY"],"ANGRY","synonym",
  "The first four all mean feeling good; ANGRY means feeling bad.",
  "Las primeras cuatro significan sentirse bien; ANGRY es sentirse mal."),
 (["MORNING","AFTERNOON","EVENING","NIGHT","MONDAY"],"MONDAY","semantic",
  "All are parts of a day; MONDAY is a day of the week.",
  "Todos son partes de un dia; MONDAY es un dia de la semana."),
 (["SLEEP","REST","NAP","DOZE","RUN"],"RUN","synonym",
  "The first four all mean resting; RUN means moving fast.",
  "Las primeras cuatro significan descansar; RUN es moverse rapido."),
 (["MOTHER","FATHER","SISTER","BROTHER","NEIGHBOR"],"NEIGHBOR","semantic",
  "All are family members; a NEIGHBOR lives near you but is not family.",
  "Todos son miembros de la familia; un NEIGHBOR vive cerca pero no es familia."),
 (["BIG","LARGE","HUGE","ENORMOUS","TINY"],"TINY","synonym",
  "The first four all mean of great size; TINY means very small.",
  "Las primeras cuatro significan de gran tamano; TINY significa muy pequeno."),
 (["SOAP","SHAMPOO","TOOTHPASTE","TOWEL","SPOON"],"SPOON","semantic",
  "All are used to get clean; a SPOON is used to eat.",
  "Todos se usan para limpiarse; una SPOON se usa para comer."),
 (["FAST","QUICK","RAPID","SWIFT","SLOW"],"SLOW","synonym",
  "The first four all mean moving with speed; SLOW is the opposite.",
  "Las primeras cuatro significan moverse con velocidad; SLOW es lo contrario."),
 (["APPLE","BANANA","ORANGE","GRAPE","CARROT"],"CARROT","semantic",
  "All are fruits; a CARROT is a vegetable.",
  "Todos son frutas; una CARROT es un vegetal."),
 (["START","BEGIN","LAUNCH","COMMENCE","FINISH"],"FINISH","synonym",
  "The first four all mean to start something; FINISH means to end it.",
  "Las primeras cuatro significan empezar algo; FINISH es terminarlo."),
 (["BED","SOFA","CHAIR","TABLE","WINDOW"],"WINDOW","semantic",
  "All are furniture you can use; a WINDOW is part of the wall.",
  "Todos son muebles que puedes usar; una WINDOW es parte de la pared."),
],

("daily", "intermediate"): [
 (["EXHAUSTED","TIRED","WEARY","DRAINED","ENERGETIC"],"ENERGETIC","synonym",
  "The first four all mean having no energy; ENERGETIC means full of it.",
  "Las primeras cuatro significan no tener energia; ENERGETIC significa estar lleno de ella."),
 (["LAUNDRY","DISHES","VACUUMING","DUSTING","GARDENING"],"GARDENING","semantic",
  "All are chores you do inside the house; GARDENING is done outside.",
  "Todos son tareas dentro de la casa; GARDENING se hace afuera."),
 (["RECIPE","INGREDIENT","OVEN","POT","BLANKET"],"BLANKET","semantic",
  "All are used to cook; a BLANKET keeps you warm in bed.",
  "Todos se usan para cocinar; una BLANKET te abriga en la cama."),
 (["HABIT","ROUTINE","CUSTOM","PRACTICE","SURPRISE"],"SURPRISE","synonym",
  "The first four all mean something you do regularly; a SURPRISE is unexpected.",
  "Las primeras cuatro son algo que haces con regularidad; una SURPRISE es inesperada."),
 (["NEIGHBORHOOD","DISTRICT","AREA","ZONE","BUILDING"],"BUILDING","synonym",
  "The first four all mean a part of a city; a BUILDING is a single structure.",
  "Las primeras cuatro son una parte de la ciudad; un BUILDING es una sola estructura."),
 (["ARGUE","QUARREL","DISPUTE","BICKER","AGREE"],"AGREE","synonym",
  "The first four all mean fighting with words; AGREE means the opposite.",
  "Las primeras cuatro significan pelear con palabras; AGREE es lo contrario."),
 (["APPOINTMENT","RESERVATION","BOOKING","SCHEDULE","CANCELLATION"],"CANCELLATION","synonym",
  "The first four all mean arranging a time; a CANCELLATION undoes it.",
  "Las primeras cuatro significan reservar un momento; una CANCELLATION lo deshace."),
 (["POLITE","COURTEOUS","RESPECTFUL","CIVIL","RUDE"],"RUDE","synonym",
  "The first four describe good manners; RUDE describes bad ones.",
  "Las primeras cuatro describen buenos modales; RUDE describe malos modales."),
 (["GROCERY","SUPERMARKET","MARKET","STORE","PHARMACY"],"PHARMACY","semantic",
  "All are places to buy food; a PHARMACY sells medicine.",
  "Todos son lugares para comprar comida; una PHARMACY vende medicinas."),
 (["BORROW","LEND","RETURN","OWE","DONATE"],"DONATE","semantic",
  "The first four all involve giving something back; DONATE means giving it away for good.",
  "Las primeras cuatro implican devolver algo; DONATE es darlo para siempre."),
 (["BASEMENT","ATTIC","HALLWAY","BALCONY","FENCE"],"FENCE","semantic",
  "All are parts of a house; a FENCE surrounds the property outside.",
  "Todos son partes de una casa; una FENCE rodea la propiedad por fuera."),
 (["WORRIED","ANXIOUS","NERVOUS","UNEASY","RELAXED"],"RELAXED","synonym",
  "The first four all mean feeling tense; RELAXED means calm.",
  "Las primeras cuatro significan sentirse tenso; RELAXED significa tranquilo."),
],

("daily", "advanced"): [
 (["METICULOUS","THOROUGH","PAINSTAKING","SCRUPULOUS","CARELESS"],"CARELESS","synonym",
  "The first four all mean very careful; CARELESS is the opposite.",
  "Las primeras cuatro significan muy cuidadoso; CARELESS es lo contrario."),
 (["RESILIENT","TOUGH","HARDY","ROBUST","FRAGILE"],"FRAGILE","synonym",
  "The first four all mean able to withstand difficulty; FRAGILE breaks easily.",
  "Las primeras cuatro significan capaz de resistir; FRAGILE se rompe facilmente."),
 (["CHORE","ERRAND","TASK","DUTY","LEISURE"],"LEISURE","synonym",
  "The first four are things you have to do; LEISURE is free time.",
  "Las primeras cuatro son cosas que debes hacer; LEISURE es tiempo libre."),
 (["FRUGAL","THRIFTY","ECONOMICAL","PRUDENT","EXTRAVAGANT"],"EXTRAVAGANT","synonym",
  "The first four mean careful with money; EXTRAVAGANT means spending too much.",
  "Las primeras cuatro significan cuidadoso con el dinero; EXTRAVAGANT es gastar de mas."),
 (["CLUTTER","MESS","DISARRAY","CHAOS","ORDER"],"ORDER","synonym",
  "The first four all mean disorganization; ORDER means everything in its place.",
  "Las primeras cuatro significan desorganizacion; ORDER es todo en su lugar."),
 (["MUNDANE","ROUTINE","ORDINARY","COMMONPLACE","EXTRAORDINARY"],"EXTRAORDINARY","synonym",
  "The first four describe everyday dullness; EXTRAORDINARY is remarkable.",
  "Las primeras cuatro describen lo cotidiano y soso; EXTRAORDINARY es notable."),
 (["CONSIDERATE","THOUGHTFUL","ATTENTIVE","CARING","INDIFFERENT"],"INDIFFERENT","synonym",
  "The first four mean paying attention to others; INDIFFERENT means not caring.",
  "Las primeras cuatro significan atender a los demas; INDIFFERENT es no importarle."),
 (["PROCRASTINATE","DELAY","POSTPONE","STALL","EXPEDITE"],"EXPEDITE","synonym",
  "The first four all mean putting things off; EXPEDITE means speeding them up.",
  "Las primeras cuatro significan dejar las cosas para despues; EXPEDITE es acelerarlas."),
 (["SEDENTARY","INACTIVE","IDLE","STATIONARY","ACTIVE"],"ACTIVE","synonym",
  "The first four all mean not moving much; ACTIVE is the opposite.",
  "Las primeras cuatro significan moverse poco; ACTIVE es lo contrario."),
 (["INSOMNIA","RESTLESSNESS","SLEEPLESSNESS","WAKEFULNESS","SLUMBER"],"SLUMBER","synonym",
  "The first four all mean being unable to sleep; SLUMBER means deep sleep.",
  "Las primeras cuatro significan no poder dormir; SLUMBER es sueno profundo."),
 (["NURTURE","RAISE","REAR","BRING UP","NEGLECT"],"NEGLECT","synonym",
  "The first four all mean taking care of a child; NEGLECT means failing to.",
  "Las primeras cuatro significan cuidar a un nino; NEGLECT es no hacerlo."),
 (["CUISINE","GASTRONOMY","COOKERY","CULINARY ARTS","APPETITE"],"APPETITE","synonym",
  "The first four are all about the art of cooking; APPETITE is the desire to eat.",
  "Las primeras cuatro son sobre el arte de cocinar; APPETITE es el deseo de comer."),
],

# ══════════════════════════════════════════════════════════
("general", "basic"): [
 (["DOG","CAT","HORSE","COW","TREE"],"TREE","semantic",
  "All are animals; a TREE is a plant.",
  "Todos son animales; un TREE es una planta."),
 (["RED","BLUE","GREEN","YELLOW","ROUND"],"ROUND","semantic",
  "All are colors; ROUND is a shape.",
  "Todos son colores; ROUND es una forma."),
 (["SUN","MOON","STAR","PLANET","CLOUD"],"CLOUD","semantic",
  "All are objects in space; a CLOUD is in our sky.",
  "Todos son objetos del espacio; una CLOUD esta en nuestro cielo."),
 (["SMALL","LITTLE","TINY","MINI","GIANT"],"GIANT","synonym",
  "The first four all mean not big; GIANT means very big.",
  "Las primeras cuatro significan no grande; GIANT significa muy grande."),
 (["DOCTOR","NURSE","DENTIST","SURGEON","TEACHER"],"TEACHER","semantic",
  "All work in health care; a TEACHER works in education.",
  "Todos trabajan en salud; un TEACHER trabaja en educacion."),
 (["RAIN","SNOW","WIND","STORM","MOUNTAIN"],"MOUNTAIN","semantic",
  "All are types of weather; a MOUNTAIN is a landform.",
  "Todos son tipos de clima; una MOUNTAIN es un accidente geografico."),
 (["ONE","TWO","THREE","FOUR","FIRST"],"FIRST","semantic",
  "All say how many; FIRST says the position in an order.",
  "Todos dicen cuantos; FIRST dice la posicion en un orden."),
 (["GUITAR","PIANO","DRUM","VIOLIN","PAINTING"],"PAINTING","semantic",
  "All are musical instruments; a PAINTING is visual art.",
  "Todos son instrumentos musicales; un PAINTING es arte visual."),
 (["EASY","SIMPLE","BASIC","STRAIGHTFORWARD","DIFFICULT"],"DIFFICULT","synonym",
  "The first four all mean not hard; DIFFICULT is the opposite.",
  "Las primeras cuatro significan que no es dificil; DIFFICULT es lo contrario."),
 (["EYE","NOSE","MOUTH","EAR","HAND"],"HAND","semantic",
  "All are parts of the face; a HAND is at the end of the arm.",
  "Todos son partes de la cara; una HAND esta al final del brazo."),
 (["BOOK","MAGAZINE","NEWSPAPER","NOVEL","RADIO"],"RADIO","semantic",
  "All are things you read; a RADIO is something you listen to.",
  "Todos son cosas que lees; un RADIO es algo que escuchas."),
 (["OLD","ANCIENT","ELDERLY","AGED","YOUNG"],"YOUNG","synonym",
  "The first four all mean having many years; YOUNG means few.",
  "Las primeras cuatro significan tener muchos anos; YOUNG significa pocos."),
],

("general", "intermediate"): [
 (["BRAVE","COURAGEOUS","FEARLESS","BOLD","COWARDLY"],"COWARDLY","synonym",
  "The first four all mean not afraid; COWARDLY means full of fear.",
  "Las primeras cuatro significan sin miedo; COWARDLY significa lleno de miedo."),
 (["RIVER","STREAM","CREEK","BROOK","POND"],"POND","synonym",
  "The first four are all moving water; a POND is still water.",
  "Las primeras cuatro son agua en movimiento; un POND es agua quieta."),
 (["INVENT","CREATE","DESIGN","DEVELOP","COPY"],"COPY","synonym",
  "The first four all mean making something new; COPY means repeating what exists.",
  "Las primeras cuatro significan hacer algo nuevo; COPY es repetir lo que ya existe."),
 (["HONEST","TRUTHFUL","SINCERE","FRANK","DECEITFUL"],"DECEITFUL","synonym",
  "The first four all mean telling the truth; DECEITFUL means lying.",
  "Las primeras cuatro significan decir la verdad; DECEITFUL es mentir."),
 (["EARTHQUAKE","HURRICANE","FLOOD","DROUGHT","HARVEST"],"HARVEST","semantic",
  "All are natural disasters; a HARVEST is a good thing for farmers.",
  "Todos son desastres naturales; una HARVEST es algo bueno para los agricultores."),
 (["INCREASE","RISE","GROW","EXPAND","SHRINK"],"SHRINK","synonym",
  "The first four all mean getting bigger; SHRINK means getting smaller.",
  "Las primeras cuatro significan hacerse mas grande; SHRINK es hacerse mas pequeno."),
 (["MUSCLE","BONE","NERVE","ORGAN","SKIN"],"SKIN","semantic",
  "All are inside the body; SKIN is on the outside.",
  "Todos estan dentro del cuerpo; la SKIN esta por fuera."),
 (["SILENT","QUIET","NOISELESS","HUSHED","DEAFENING"],"DEAFENING","synonym",
  "The first four all mean without sound; DEAFENING means extremely loud.",
  "Las primeras cuatro significan sin sonido; DEAFENING significa extremadamente fuerte."),
 (["EVIDENCE","PROOF","CONFIRMATION","VERIFICATION","GUESS"],"GUESS","synonym",
  "The first four all mean something that shows the truth; a GUESS is uncertain.",
  "Las primeras cuatro son algo que demuestra la verdad; un GUESS es incierto."),
 (["ORCHESTRA","CHOIR","BAND","ENSEMBLE","SOLOIST"],"SOLOIST","semantic",
  "All are groups of musicians; a SOLOIST performs alone.",
  "Todos son grupos de musicos; un SOLOIST actua solo."),
 (["PERMANENT","LASTING","ENDURING","EVERLASTING","TEMPORARY"],"TEMPORARY","synonym",
  "The first four all mean going on forever; TEMPORARY means for a short time.",
  "Las primeras cuatro significan que dura para siempre; TEMPORARY es por poco tiempo."),
 (["VOLCANO","GLACIER","CANYON","DESERT","BRIDGE"],"BRIDGE","semantic",
  "All are natural landforms; a BRIDGE is built by people.",
  "Todos son formaciones naturales; un BRIDGE lo construyen las personas."),
],

("general", "advanced"): [
 (["AMBIGUOUS","VAGUE","UNCLEAR","OBSCURE","EXPLICIT"],"EXPLICIT","synonym",
  "The first four all mean hard to understand; EXPLICIT means perfectly clear.",
  "Las primeras cuatro significan dificil de entender; EXPLICIT significa perfectamente claro."),
 (["ABUNDANT","PLENTIFUL","AMPLE","COPIOUS","SCARCE"],"SCARCE","synonym",
  "The first four all mean there is a lot; SCARCE means there is very little.",
  "Las primeras cuatro significan que hay mucho; SCARCE significa que hay muy poco."),
 (["INEVITABLE","UNAVOIDABLE","CERTAIN","INESCAPABLE","OPTIONAL"],"OPTIONAL","synonym",
  "The first four mean it will happen no matter what; OPTIONAL means you can choose.",
  "Las primeras cuatro significan que pasara sin remedio; OPTIONAL significa que puedes elegir."),
 (["DIMINISH","DECLINE","DWINDLE","WANE","SURGE"],"SURGE","synonym",
  "The first four all mean becoming less; SURGE means rising sharply.",
  "Las primeras cuatro significan disminuir; SURGE es subir de golpe."),
 (["ADVOCATE","SUPPORTER","PROPONENT","CHAMPION","OPPONENT"],"OPPONENT","synonym",
  "The first four all mean someone who defends an idea; an OPPONENT fights against it.",
  "Las primeras cuatro son alguien que defiende una idea; un OPPONENT la combate."),
 (["PLAUSIBLE","CREDIBLE","BELIEVABLE","CONVINCING","ABSURD"],"ABSURD","synonym",
  "The first four all mean it could be true; ABSURD means it makes no sense.",
  "Las primeras cuatro significan que podria ser cierto; ABSURD significa que no tiene sentido."),
 (["TRANSPARENT","OPEN","CANDID","FORTHRIGHT","SECRETIVE"],"SECRETIVE","synonym",
  "The first four all mean hiding nothing; SECRETIVE means hiding everything.",
  "Las primeras cuatro significan no ocultar nada; SECRETIVE es ocultarlo todo."),
 (["CATALYST","TRIGGER","STIMULUS","IMPETUS","OBSTACLE"],"OBSTACLE","synonym",
  "The first four all cause something to start; an OBSTACLE stops it.",
  "Las primeras cuatro hacen que algo empiece; un OBSTACLE lo detiene."),
 (["EPIDEMIC","OUTBREAK","PANDEMIC","PLAGUE","REMEDY"],"REMEDY","semantic",
  "All are widespread diseases; a REMEDY is the cure.",
  "Todos son enfermedades extendidas; un REMEDY es la cura."),
 (["PRAGMATIC","PRACTICAL","REALISTIC","SENSIBLE","IDEALISTIC"],"IDEALISTIC","synonym",
  "The first four deal with things as they are; IDEALISTIC deals with how they should be.",
  "Las primeras cuatro tratan las cosas como son; IDEALISTIC como deberian ser."),
 (["METICULOUS","RIGOROUS","EXACTING","PRECISE","SLOPPY"],"SLOPPY","synonym",
  "The first four all mean extremely careful; SLOPPY means done badly.",
  "Las primeras cuatro significan extremadamente cuidadoso; SLOPPY significa mal hecho."),
 (["UNPRECEDENTED","UNPARALLELED","UNIQUE","UNMATCHED","ROUTINE"],"ROUTINE","synonym",
  "The first four mean never seen before; ROUTINE means it happens all the time.",
  "Las primeras cuatro significan nunca visto antes; ROUTINE significa que pasa siempre."),
],
}
