# -*- coding: utf-8 -*-
"""
Palabras REALES avanzadas (C1-C2) para el nivel Advanced de
IS IT A REAL WORD, con definicion bilingue en el formato de
definitions.json  ->  {"en": "...", "es": "..."}

Sesgo intencional: negocios, tramites, migracion y trabajo,
que es la meta economica del alumno de Omar.
"""

ADVANCED = {
"ACCOUNTABLE": ("responsible for what you do and able to explain it",
                "responsable de lo que haces y capaz de explicarlo"),
"ACKNOWLEDGE": ("to accept or admit that something is true",
                "aceptar o admitir que algo es cierto"),
"ADVOCATE": ("a person who publicly supports a cause",
             "una persona que apoya publicamente una causa"),
"AMBIGUOUS": ("having more than one possible meaning",
              "que tiene mas de un significado posible"),
"ANTICIPATE": ("to expect something before it happens",
               "esperar algo antes de que ocurra"),
"APPRAISAL": ("an official judgment of value or quality",
              "una evaluacion oficial de valor o calidad"),
"ARBITRARY": ("decided without a clear or fair reason",
              "decidido sin una razon clara ni justa"),
"ASSERTIVE": ("confident and direct when saying what you want",
              "seguro y directo al decir lo que quieres"),
"AUSTERITY": ("strict control of spending money",
              "control estricto del gasto de dinero"),
"BENCHMARK": ("a standard used to compare things",
              "un estandar que se usa para comparar cosas"),
"BREACH": ("the breaking of a rule or agreement",
           "el incumplimiento de una regla o un acuerdo"),
"BUREAUCRACY": ("a system with too many official rules and steps",
                "un sistema con demasiadas reglas y tramites oficiales"),
"CANDID": ("honest and direct, even when it is difficult",
           "honesto y directo, incluso cuando es dificil"),
"COHERENT": ("clear and logically connected",
             "claro y conectado con logica"),
"COLLATERAL": ("property promised to guarantee a loan",
               "un bien que se promete para garantizar un prestamo"),
"COMMODITY": ("a raw product that is bought and sold",
              "un producto basico que se compra y se vende"),
"COMPELLING": ("so strong or interesting that it convinces you",
               "tan fuerte o interesante que te convence"),
"COMPLIANCE": ("the act of obeying a rule or a law",
               "el acto de cumplir una regla o una ley"),
"CONCEDE": ("to admit that you have lost or that you are wrong",
            "admitir que perdiste o que estas equivocado"),
"CONSENSUS": ("general agreement within a group",
              "acuerdo general dentro de un grupo"),
"CONSTRAINT": ("something that limits what you can do",
               "algo que limita lo que puedes hacer"),
"CONTINGENCY": ("a plan for something that might happen",
                "un plan para algo que podria pasar"),
"CREDENTIAL": ("a document that proves your qualification",
               "un documento que comprueba tu calificacion"),
"CUMBERSOME": ("heavy, slow or difficult to handle",
               "pesado, lento o dificil de manejar"),
"DEPRECIATE": ("to lose value as time passes",
               "perder valor con el paso del tiempo"),
"DETERRENT": ("something that stops people from doing something",
              "algo que impide que la gente haga algo"),
"DILIGENT": ("working carefully and with steady effort",
             "que trabaja con cuidado y esfuerzo constante"),
"DISCERNING": ("able to judge quality well",
               "capaz de juzgar bien la calidad"),
"DISCLOSURE": ("the act of making information public",
               "el acto de hacer publica una informacion"),
"DISCRETION": ("the freedom to decide something for yourself",
               "la libertad de decidir algo por ti mismo"),
"DISPARITY": ("a big and unfair difference",
              "una diferencia grande e injusta"),
"DIVERGENT": ("going in different directions",
              "que va en direcciones diferentes"),
"ELIGIBLE": ("allowed to do or to receive something",
             "que cumple los requisitos para hacer o recibir algo"),
"EMBARK": ("to start something new and important",
           "emprender algo nuevo e importante"),
"ENDORSE": ("to publicly support or approve something",
            "apoyar o aprobar algo publicamente"),
"ENTITLEMENT": ("the right to have or receive something",
                "el derecho a tener o recibir algo"),
"ESCALATE": ("to become more serious or more intense",
             "volverse mas serio o mas intenso"),
"EXEMPT": ("free from a duty that others must follow",
           "libre de una obligacion que otros deben cumplir"),
"EXPEDITE": ("to make a process happen faster",
             "hacer que un proceso ocurra mas rapido"),
"FEASIBLE": ("possible to do in practice",
             "posible de hacer en la practica"),
"FISCAL": ("relating to government money and taxes",
           "relativo al dinero y los impuestos del gobierno"),
"FORFEIT": ("to lose a right as a punishment",
            "perder un derecho como castigo"),
"FRAUDULENT": ("dishonest in order to gain money",
               "deshonesto con el fin de obtener dinero"),
"GRIEVANCE": ("a formal complaint about unfair treatment",
              "una queja formal por trato injusto"),
"IMMINENT": ("about to happen very soon",
             "que va a ocurrir muy pronto"),
"IMPARTIAL": ("not favoring any side",
              "que no favorece a ningun lado"),
"INCENTIVE": ("something that encourages you to act",
              "algo que te motiva a actuar"),
"INCUMBENT": ("the person currently holding a position",
              "la persona que ocupa el cargo actualmente"),
"INDIGENOUS": ("originally from a particular place",
               "originario de un lugar determinado"),
"INEVITABLE": ("certain to happen and impossible to avoid",
               "que seguro va a pasar y no se puede evitar"),
"INFERENCE": ("a conclusion based on evidence",
              "una conclusion basada en evidencia"),
"INHERENT": ("existing as a natural part of something",
             "que existe como parte natural de algo"),
"INSOLVENT": ("unable to pay what you owe",
              "incapaz de pagar lo que debes"),
"INTEGRITY": ("the quality of being honest and having strong morals",
              "la cualidad de ser honesto y tener principios firmes"),
"INTERMITTENT": ("stopping and starting again repeatedly",
                 "que se detiene y arranca de nuevo repetidamente"),
"LEVERAGE": ("the power to influence a result",
             "el poder de influir en un resultado"),
"LIABILITY": ("legal responsibility for something",
              "responsabilidad legal por algo"),
"LITIGATION": ("the process of taking legal action in court",
               "el proceso de llevar una accion legal a un tribunal"),
"LUCRATIVE": ("producing a large amount of money",
              "que produce mucho dinero"),
"MANDATE": ("an official order or the authority to act",
            "una orden oficial o la autoridad para actuar"),
"MEDIATE": ("to help two sides reach an agreement",
            "ayudar a dos partes a llegar a un acuerdo"),
"MERGER": ("the joining of two companies into one",
           "la union de dos empresas en una"),
"METICULOUS": ("very careful about small details",
               "muy cuidadoso con los detalles pequenos"),
"MITIGATE": ("to make something less severe",
             "hacer que algo sea menos grave"),
"NEGLIGENT": ("failing to take proper care of something",
              "que no cuida algo como deberia"),
"OBSOLETE": ("no longer used because it is too old",
             "que ya no se usa porque es muy viejo"),
"ONEROUS": ("difficult and needing a lot of effort",
            "dificil y que requiere mucho esfuerzo"),
"OUTSOURCE": ("to pay another company to do part of your work",
              "pagar a otra empresa para que haga parte de tu trabajo"),
"PARAMOUNT": ("more important than anything else",
              "mas importante que cualquier otra cosa"),
"PERTINENT": ("directly relevant to the matter",
              "directamente relevante para el asunto"),
"PLAUSIBLE": ("seeming reasonable or probably true",
              "que parece razonable o probablemente cierto"),
"PRAGMATIC": ("dealing with things in a practical way",
              "que maneja las cosas de forma practica"),
"PRECEDENT": ("an earlier case used as an example for later ones",
              "un caso anterior que sirve de ejemplo para los siguientes"),
"PRELIMINARY": ("happening before the main event",
                "que ocurre antes del evento principal"),
"PREVALENT": ("common in a particular place or time",
              "comun en un lugar o momento determinado"),
"PROCUREMENT": ("the process of buying supplies for an organization",
                "el proceso de comprar suministros para una organizacion"),
"PROFICIENT": ("very skilled at something",
               "muy habil en algo"),
"PROVISION": ("a condition included in an agreement or law",
              "una condicion incluida en un acuerdo o una ley"),
"PRUDENT": ("careful and sensible about the future",
            "cuidadoso y sensato respecto al futuro"),
"RECIPROCAL": ("given by both sides in equal measure",
               "que ambas partes dan en igual medida"),
"REDUNDANT": ("no longer needed, or repeated without purpose",
              "que ya no se necesita, o que se repite sin proposito"),
"REIMBURSE": ("to pay someone back the money they spent",
              "devolverle a alguien el dinero que gasto"),
"REMITTANCE": ("money sent to someone in another place",
               "dinero enviado a alguien en otro lugar"),
"RESILIENT": ("able to recover quickly from difficulty",
              "capaz de recuperarse rapido de una dificultad"),
"SCRUTINY": ("very careful and critical examination",
             "examen muy cuidadoso y critico"),
"STAGNANT": ("not moving and not developing",
             "que no se mueve ni se desarrolla"),
"STIPULATE": ("to state a requirement inside an agreement",
              "establecer un requisito dentro de un acuerdo"),
"SUBSEQUENT": ("coming after something else",
               "que viene despues de otra cosa"),
"SUBSIDIARY": ("a company controlled by a larger company",
               "una empresa controlada por otra mas grande"),
"SUBSTANTIATE": ("to prove something with evidence",
                 "comprobar algo con evidencia"),
"SURPLUS": ("more than what is needed",
            "mas de lo que se necesita"),
"SUSTAINABLE": ("able to continue for a long time without harm",
                "que puede continuar mucho tiempo sin causar dano"),
"TANGIBLE": ("real and able to be touched or measured",
             "real y que se puede tocar o medir"),
"TENTATIVE": ("not final and likely to change",
              "que no es definitivo y puede cambiar"),
"THRESHOLD": ("the level at which something begins",
              "el nivel en el que algo comienza"),
"UNANIMOUS": ("agreed by absolutely everyone",
              "acordado por absolutamente todos"),
"UNDERMINE": ("to weaken something gradually",
              "debilitar algo poco a poco"),
"UNPRECEDENTED": ("never having happened before",
                  "que nunca habia ocurrido antes"),
"VIABLE": ("able to work successfully",
           "capaz de funcionar con exito"),
"VOLATILE": ("changing quickly and unpredictably",
             "que cambia rapido y de forma impredecible"),
"WAIVER": ("a document in which you give up a right",
           "un documento en el que renuncias a un derecho"),
"YIELD": ("to produce a result, a profit or a crop",
          "producir un resultado, una ganancia o una cosecha"),
"ARREARS": ("money that is owed and was not paid on time",
            "dinero que se debe y no se pago a tiempo"),
"ASCERTAIN": ("to find out something for certain",
              "averiguar algo con certeza"),
"COMPRISE": ("to consist of several parts",
             "estar formado por varias partes"),
"CONVENE": ("to bring people together for a meeting",
            "reunir a personas para una junta"),
"DEPLOY": ("to move people or resources into position to be used",
           "mover personas o recursos a su posicion para usarlos"),
"ENUMERATE": ("to list things one by one",
              "enumerar cosas una por una"),
"INDEMNITY": ("protection or payment against loss or damage",
              "proteccion o pago frente a una perdida o dano"),
"STREAMLINE": ("to make a process simpler and faster",
               "hacer que un proceso sea mas simple y rapido"),
"ADHERE": ("to follow a rule or stick firmly to something",
           "cumplir una regla o adherirse firmemente a algo"),
"ALLOCATE": ("to give out money or resources for a purpose",
             "asignar dinero o recursos para un fin"),
"CURTAIL": ("to reduce or limit something",
            "reducir o limitar algo"),
"DEFAULT": ("to fail to pay a debt as agreed",
            "dejar de pagar una deuda como se acordo"),
"ENDEAVOR": ("a serious attempt to achieve something",
             "un intento serio de lograr algo"),
"FORESIGHT": ("the ability to plan for the future",
              "la capacidad de prever y planear el futuro"),
"HINDRANCE": ("something that makes progress difficult",
              "algo que dificulta el avance"),
"OVERSIGHT": ("the act of supervising, or a small mistake",
              "la supervision de algo, o un descuido pequeno"),
"PROSPECTIVE": ("likely to happen or to become something in the future",
                "que probablemente ocurra o llegue a ser algo en el futuro"),
"UNDERTAKE": ("to accept responsibility for a task and begin it",
              "asumir la responsabilidad de una tarea y comenzarla"),
}
